<!DOCTYPE html>
<html>
<head>
	<title>Travelo</title>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="styles.css">

</head>
<body>


	<!--Navbar-->
	<div class="navbar">
		<div class="logo">
			<img src="icon.png"/>
		</div>
		<div class="nav">
			<ul>
				<li><a href="home.php">Home</a></li>
				<li><a href="about.php" class="active">About Us</a></li>
				<li><a href="packages.php">Packages</a></li>
				<li><a href="gallery.php">Gallery</a></li>
				<li><a href="contact.php">Contact Us</a></li>
			</ul>
		</div>
	</div>

	<div class="side-nav">
	<ul>
		<li><a href="login.php" class="sidenav-links" >DASHBOARD</a></li>
		<li><a href="contact.php" class="sidenav-links" >SUBMIT QUERY</a></li>
		<li><a href="booking.php" class="sidenav-links" >BOOK NOW</a></li>			
	</ul>
	<div class="triangle-down"></div>
</div>

	<!--About US-->
	
	<div class="about-head">
		<h1>Discover more about our services!</h1>      
	</div>
	<div class="about-section">
		<div class="info">

			<h2>Who We Are?</h2>
			<p>We are the private tour operators offering our services for the travel and tourism activities in Kashmir and other regions of Pakistan having our offices in Karachi and Azad Kashmir.</p>

			<h2>Our Aim</h2>
			<p>Travelo.pk aims to provide its services for the people want to visit the different tourist destination in Pakistan. We want to make the different beautiful areas of Pakistan to be accessed easily by the people so that they would see the real beauty of our country. Also, our aim is to preserve the preserve our cultural heritage making the others familiarize with the culture of these beautiful destinations.</p>

			<h2>Our Vision</h2>
			<p>Tourism in Pakistan is seen to be flourishing and every year a large number of people ask the different travel and tourism services to plan their trip to the Kashmir and the other northern areas of Pakistan. But still it is believed that our tourism destinations have the potential to attract more visitors; therefore for ensuring the quality services, we try our best so that not only our customers would be experiencing the best services but also we would be able to strengthen the domestic tourism in Pakistan.</p>

			<h2>Our Team</h2>
			<p>We have the experts in our team who have the knowledge about the different places of Pakistan so that we would be providing you with the best packages. We want to provide the best travel and tourism services in Pakistan; whether you belong to Islamabad, Lahore or Karachi we would make your trip a memorable one.</p>

		</div>

		<!--Sidebar-->

		<div class="aside">
			<h2>Why Book with Us?</h2>
			<h3>Low Rates</h3>
			<p>Get the best rates, or get a refund.
			No booking fees. Save money!</p>

			<h3>Largest Selection</h3>
			<p>150,000+ hotels worldwide
				100+ Pakistani Hotels
			Online booking in 13 cities & 6 summer destinations</p>

			<h3>We're Always Here</h3>
			<p>Call us from 9 AM to 5 PM
				Get 24-hour support before, during, and after your trip through email
				<br>
			E: info@tourplanner.pk</p>
		</div>
	</div>

	<!--Footer-->

	<?php  include("Footer.php"); ?>

	<script type="text/javascript" src="projectjs.js"></script>

</body>
</html>